# Generated by Django 5.1.6 on 2025-02-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reg_number',
            field=models.CharField(default='default_reg_number', max_length=30, unique=True),
        ),
    ]
