# Generated by Django 5.1.6 on 2025-02-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0002_media_news_notice_delete_blog_alter_event_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='partner_logos/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
