# Generated by Django 5.1.6 on 2025-02-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0003_partnerlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='school_activities/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
